import Page from './Page';
import Browser from './Browser';
import { RequestWorker, Callback, Filter, CrawlerOptions, Listener, PageOptions } from './base';
export default class Crawler {
    private _queue;
    private _concurrency;
    private _timeout;
    private _headers;
    private _filter;
    private _callback?;
    private _emitter;
    private _eventTypeCount;
    private _readyExitTimer;
    browser: Browser;
    constructor(options?: CrawlerOptions);
    _updateReadyExitTimer(): void;
    _initQueue(worker: RequestWorker, concurrency: number): void;
    _getPageCallback(page: Page): Callback;
    _getPageCallbackWrapper(page: Page): Callback;
    on<T extends string | symbol>(event: T, listener: Listener<T>): this;
    off(event: string | symbol, listener: (...args: any[]) => void): this;
    timeout(timeout: number): this;
    callback(callback: Callback): this;
    filter(filter: Filter): this;
    add(page: Page | Page[]): this;
    addPage(page: PageOptions | PageOptions[]): void;
    start(): void;
    pause(): void;
    stop(): any;
}
