import Page from './Page';
import { Callback, Filter, CrawlerOptions, Listener, PageOptions } from './base';
export default class Crawler {
    private _queue;
    private _concurrency;
    private _timeout;
    private _headers;
    private _proxy;
    private _filter;
    private _callback?;
    private _end?;
    private _emitter;
    private _readyExitTimer;
    private _pageId;
    private _hideDefaultLog;
    default: import("./base").CrawlerDefaultOptions;
    private get _eventTypeCount();
    constructor(options?: CrawlerOptions);
    static use(plugin: Function): typeof Crawler;
    _initHeaders(headers: Record<string, any>): {
        'User-Agent': string;
    } & Record<string, any>;
    _getDefaultConfig(): import("./base").CrawlerDefaultOptions;
    _callEndFunction(): void;
    _updateReadyExitTimer(): Promise<void>;
    _worker(page: Page, done: Callback): Promise<void>;
    _initQueue(concurrency: number): void;
    _getPageCallback(page: Page): Callback;
    _getPageCallbackWrapper(page: Page): Callback;
    on<T extends string | symbol>(event: T, listener: Listener<T>): this;
    off(event: string | symbol, listener: (...args: any[]) => void): this;
    timeout(timeout: number): this;
    callback(callback: Callback): this;
    filter(filter: Filter): this;
    add(page: Page | Page[]): this;
    addPage(page: PageOptions | PageOptions[]): this;
    start(): void;
    pause(): void;
    stop(): any;
}
